In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
new_arr=np.add(arr,1)

new_arr2=np.subtract(arr,20)
new_arr3=np.power(arr,3)
new_arr3

In [ ]:
a=np.array([3,4,5])
b=np.array([1,2,3])
c=np.add(a,b)
d=np.subtract(a,b)
e= np.multiply(a,b)
print(c)
print(d)
print(e)

In [9]:
sin_a=np.sin(a)
cos_a=np.cos(a)
print(sin_a)
print(cos_a)

[ 0.14112001 -0.7568025  -0.95892427]
[-0.9899925  -0.65364362  0.28366219]


In [11]:
integer_arr=np.array([-4,-3,-1,0,3,4,5,6])
abs_arr=np.abs(integer_arr)
abs_arr

array([4, 3, 1, 0, 3, 4, 5, 6])